const mongoose = require("mongoose");

// Aggregated summary for a paper — computed after all questions are analyzed
// This is what the dashboard reads from, not the raw Question documents

const analysisResultSchema = new mongoose.Schema(
  {
    paperId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Paper",
      required: true,
      unique: true,            // One summary per paper
    },

    // --- Overall Scores ---
    overallDifficultyScore: {
      type: Number,            // Weighted average, 1-10
    },
    syllabusCoveragePercent: {
      type: Number,            // % of questions that matched syllabus
    },
    outOfSyllabusCount: {
      type: Number,
      default: 0,
    },

    // --- Distributions (used directly by Recharts) ---
    difficultyDistribution: {
      easy: { type: Number, default: 0 },
      medium: { type: Number, default: 0 },
      hard: { type: Number, default: 0 },
    },
    bloomsDistribution: {
      remember: { type: Number, default: 0 },
      understand: { type: Number, default: 0 },
      apply: { type: Number, default: 0 },
      analyze: { type: Number, default: 0 },
      evaluate: { type: Number, default: 0 },
      create: { type: Number, default: 0 },
    },
    complexityDistribution: {
      surface: { type: Number, default: 0 },
      intermediate: { type: Number, default: 0 },
      deep: { type: Number, default: 0 },
      complex: { type: Number, default: 0 },
    },

    // --- Topic Coverage ---
    topicsCovered: [String],
    topicsNotCovered: [String],   // In syllabus but not in paper

    // --- Raw insights from agent ---
    insights: {
      type: String,              // Paragraph generated by LLM
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model("AnalysisResult", analysisResultSchema);
